Repository pagopa/pagopa-biz-events-datastore, pull requests merged in 2022-12, with the labels that each got.

#12 Update pipelines
  .devops/deploy-pipelines.yml
  integration-test/src/config/.env.uat
Labels: ignore-for-release

#14 feat: add performance-test pipeline
  .devops/performance-test-pipelines.yml
  load-test/src/uat.environment.json
  performance-test/README.md
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx.conf
  performance-test/run_performance_test.sh
  performance-test/src/README.md
  performance-test/src/bizevent_processor.js
  performance-test/src/dev.environment.json
  performance-test/src/local.environment.json
  performance-test/src/modules/common.js
  performance-test/src/modules/datastore_client.js
  performance-test/src/modules/event_hub_client.js
  performance-test/src/test-types/load.json
  performance-test/src/test-types/spike.json
  performance-test/src/test-types/stress.json
  performance-test/src/uat.environment.json
Labels: enhancement

#16 [PAGOPA-18] fix retry: changed behaviour
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichment.java
  src/main/java/it/gov/pagopa/bizeventsdatastore/client/PaymentManagerClient.java
  src/main/java/it/gov/pagopa/bizeventsdatastore/entity/BizEvent.java
  src/main/java/it/gov/pagopa/bizeventsdatastore/entity/Psp.java
  src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichmentTest.java
Labels: bug
