Repository pagopa/pagopa-biz-events-datastore, pull requests merged in 2023-09, with the labels that each got.

#39 feat: adding transactionId field to transaction PAGOPA-1193
  src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichment.java
  src/main/java/it/gov/pagopa/bizeventsdatastore/entity/Transaction.java
  src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichmentTest.java
  src/test/resources/payment-manager/bizEventPM.json
  src/test/resources/payment-manager/bizEventWithTransactionDetails.json
Labels: enhancement, ignore-for-release

#40 feat: [PAGOPA-1085] duplicated bizevent
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
  src/main/java/it/gov/pagopa/bizeventsdatastore/client/RedisClient.java
  src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStoreTest.java
  src/test/java/it/gov/pagopa/bizeventsdatastore/client/RedisClientTest.java
Labels: bug, enhancement, size/large

#41 fix: Upd chart 2.x
  .github/workflows/deploy_with_github_runner.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small

#42 feat: [PAGOPA-1230] add prefix
  src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
Labels: enhancement, size/small

#43 feat: [PAGOPA-1247] upgrade ext bundle [4.0.0, 5.0.0)
  Dockerfile
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  host.json
  local.settings.json.example
  pom.xml
  src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichment.java
  src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventTimerTrigger.java
  src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
Labels: enhancement, size/small
