Repository pagopa/pagopa-biz-events-datastore, pull requests merged in 2024-05, with the labels that each got.

#65 chore: Log_refactoring + add parallel stream
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToViewDataStoreTimerTrigger.java
  src/main/java/it/gov/pagopa/bizeventsdatastore/service/impl/BizEventToViewServiceImpl.java
Labels: size/small, minor

#66 chore: Enabled trx list view
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, patch

#67 chore: Migrazione redis multiAZ
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch

#69 Fix uat helm
  helm/values-uat.yaml
Labels: size/small

#71 chore: Ingestion pre PROD release
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToViewDataStoreTimerTrigger.java
Labels: patch
